name: Playwright Tests

on:
  push:
    branches:
      - main

  pull_request:

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: actions/checkout@v4
      with:
        repository: hathitrust/firebird-common
        path: firebird-common

    - name: Build firebird
      run: docker compose run firebird ./bin/build.sh

    - name: Run tests
      run: docker compose run -e CI=true playwright

    - uses: actions/upload-artifact@v4
      if: ${{ failure() }}
      with:
        name: test-results
        path: playwright/test-results/
        retention-days: 21
