name: Playwright Tests
on: push
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - name: Check out with submodules
      uses: actions/checkout@v3
      with:
        submodules: true

    - name: Set up tests
      run: docker compose build

    - name: Run tests
      run: docker compose run -e CI=true playwright

    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: playwright-report
        path: playwright/test-results/
