name: Run Tests

on:
  push:
    branches:
      - main

  pull_request:

jobs:
  # Run tests
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out with submodules
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          submodules: true

      - name: Set up tests
        run: docker compose build

      - name: Run PHPUnit tests
        run: docker compose run phpunit
